---

- name: Clear all docker containers
  hosts: host
  remote_user: docker

  tasks:
    - name: Delete all docker containers
      shell: "docker rm -f $(docker ps -a -q)"
      ignore_errors: yes
      no_log: yes