---

- name: Update apt cache if needed
  apt: update_cache=yes cache_valid_time=3600

- name: Install required tools
  apt: name={{ item }} state=present
  with_items:
    - sudo
    - docker.io
    - python-pip

- name: Install python required packages
  pip: name={{ item }} state=present
  with_items:
    - docker-py

- name: Create docker user
  user: name="{{ user_name }}" group="{{ user_group }}"

- name: Upload SSH key for docker user
  authorized_key: >
    user="{{ user_name }}"
    key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
