---
- name: Install required tools
  apt: name={{ item }} state=present
  with_items:
    - docker

- name: Install python required packages
  pip: name={{ item }} state=present
  with_items:
    - docker-py