---

- name: Make sure folder library exists with subfolders
  file: >
    state=directory
    recurse=yes
    path="{{ item }}"
  with_items:
    - "{{ library_path }}/Downloads"
    - "{{ library_path }}/Series"
    - "{{ library_path }}/Movies"

- name: Install Owncloud
  docker:
    docker_api_version: "{{ docker_version }}"
    net: bridge
    name: owncloud
    detach: yes
    restart_policy: always
    ports:
      - "{{ owncloud_port }}:80"
    volumes:
      - "{{ library_path }}:/var/www/html/data/admin/files"
    env:
      VIRTUAL_HOST: cloud.lobr.fr
    image: owncloud:latest
    state: started

- name: Install Deluge
  docker:
    docker_api_version: "{{ docker_version }}"
    net: bridge
    name: deluge
    restart_policy: always
    ports:
      - 8112:8112
    volumes:
      - "{{ library_path }}/Downloads:/downloads"
    env:
      PUID: "{{ puid }}"
      PGID: "{{ pgid }}"
      VIRTUAL_HOST: torrent.lobr.fr
      VIRTUAL_PORT: 8112
    image: linuxserver/deluge
    state: started

- name: Install Plex
  docker:
    docker_api_version: "{{ docker_version }}"
    net: host
    name: plex
    restart_policy: always
    expose:
      - 32400
    volumes:
      - "{{ library_path }}/Series:/data/tvshows"
      - "{{ library_path }}/Movies:/data/movies"
    env:
      PUID: "{{ puid }}"
      PGID: "{{ pgid }}"
      VERSION: plexpass
      VIRTUAL_HOST: plex.lobr.fr
    image: linuxserver/plex
    state: started

- debug: msg="Owncloud -> you need to set the following parameter in Owncloud's config 'filesystem_check_changes' => 1."
- debug: msg="Deluge -> credentials are admin/deluge. You need to set up download folder to /downloads."